2019-11-18 10:38:11,502 ERROR: Exception on /index [GET] [in c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Michael.Mistarz\python_laptop\flask\flask-tutorial\app\routes.py", line 28, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-11-18 10:38:12,263 ERROR: Exception on /index [GET] [in c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py:1891]
Traceback (most recent call last):
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\_compat.py", line 39, in reraise
    raise value
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask\app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "c:\users\michael.mistarz\.virtualenvs\flask-tutorial-xq1tyqdp\lib\site-packages\flask_login\utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\Michael.Mistarz\python_laptop\flask\flask-tutorial\app\routes.py", line 28, in index
    page, app.config['POSTS_PER_PAGE'], False)
KeyError: 'POSTS_PER_PAGE'
2019-11-18 10:38:28,574 INFO: Microblog startup [in C:\Users\Michael.Mistarz\python_laptop\flask\flask-tutorial\app\__init__.py:41]
